# Generated by Django 4.2.11 on 2024-03-31 20:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_portfoliosummary_stock_userstock_delete_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioSummary',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('dividend', 'Dividend'), ('growth', 'Growth'), ('value', 'Value'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='UserStock',
        ),
    ]
